[pytest]
pythonpath = .
addopts = --import-mode=importlib --alluredir=allure-results
markers =
    register_user: Регистрация нового пользователя
    login_user: Авторизация пользователя
    ui: UI тесты
    smoke: Дымовые тесты
    positive: Позитивные тесты
    negative: Негативные тесты
    incorrect_login_user: Авторизация с неверными данными
    register_exist_email: Регистрация с существующим email
    contact_us: Форма обратной связи
    view_product: Просмотр карточки товара
    search_product: Поиск товаров
    subscribe: Подписка на рассылку
    subscribe_from_home: Подписка на рассылку с главной страницы
    subscribe_from_cart: Подписка на рассылку со страницы корзины
    purchase: Оформление заказа
    add_products_in_cart: Добавление товаров в корзину
    add_product_in_cart_from_product_page: Добавление товара со страницы товара
    register_before_checkout: Регистрация перед оформлением заказа
    register_while_checkout: Регистрация со страницы корзины
