[pytest]
pythonpath = .
addopts = --import-mode=importlib
markers =
    register_user: Регистрация нового пользователя
    login_user: Авторизация пользователя
    ui: UI тесты
    smoke: Дымовые тесты
    positive: Позитивные тесты
    negative: Негативные тесты
    incorrect_login_user: Авторизация с неверными данными
    register_exist_email: Регистрация с существующим email
    contact_us: Форма обратной связи
    view_product: Просмотр карточки товара
    search_product: Поиск товаров
    subscribe: Подписка на рассылку
    subscribe_from_home: Подписка на рассылку с главной страницы
